baseURL = "https://nayuta-ai.github.io/mysite/"
languageCode = 'en-us'
title = 'My Engineer Blog'
theme = "hugo-theme-stack"

[menu]
[[menu.main]]
# identifier = "posts"
# name = "posts"
# url = "/posts/"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nayuta-ai"
[menu.social.params]
icon = "brand-github"

[params.article]
toc = true
readingTime = false
